### ISSUE TITLE
Microsoft Window Inaccessible

### ISSUE THREAD

**Issue by Trendity** [retrixe/EnderChat#18] opened 2024-03-09 05:27 UTC
To log in for premium accounts it brings up the Microsoft login page but The page is completely non-interactive. I don't know if maybe it is a framed page within the app itself with possibly a except all cookies or something right outside the frame that I cannot access. But touching anywhere on the screen does absolutely nothing until I hit back to get out of it.

Server I'll log into does not accept anything but premium at this time. I tried offline mode but it just kicks me out saying this is not a premium account.

**Comment by retrixe** [comment] 2024-03-09 08:36
Duplicate of #16

**Comment by retrixe** [comment] 2024-03-09 14:47
No problem, I'll leave this open for now until the fix makes its way to the Play Store

**Closed** 2024-12-24 22:20 UTC
Labels: bug, duplicate
