### ISSUE TITLE
E-Mail Input field in Microsoft Account Windows completly unclickable

### ISSUE THREAD

**Issue by IvvyDevMC** [retrixe/EnderChat#16] opened 2023-10-12 20:30 UTC
When attempting to add a new Microsoft Account, the oauth Window's e-mail field can Not be interacted with.

**Comment by retrixe** [comment] 2023-10-12 22:37
Please provide more details about:
- Which version of EnderChat
- Which version of Android, and if you're running any ROM or not
- Which Android device (e.g. Pixel 7, Xiaomi Redmi Note 12, etc)

This issue is known to have existed, however, it was fixed in recent builds, a release will come soon with 1.20.2 support which should address this issue as well. You can try this build of https://github.com/retrixe/EnderChat/commit/86d75b50df84635abc72bbc89fb46f7e2d25f5c1 and see if the issue is fixed:
[app-release.zip](https://github.com/retrixe/EnderChat/files/12887561/app-release.zip)

**Closed** 2023-11-06 12:42 UTC
Labels: bug, question
